MODEL: 'deeplab' #or 'unet'
parameters:
  NUM_CLASSES: 20
  INPUT_SHAPE: [320, 416, 3]
  BATCH_SIZE: 2
  LEARNING_RATE: 0.001
  NUM_EPOCHS: 100
  RANDOM_SEED: 42
  DL_BACKBONE: 'resnet50'
paths:
  dataset_path: "/content/drive/MyDrive/MulticlassSegment-main/data"
  output: "/content/drive/MyDrive/MulticlassSegment-main/output"
checkpoint:
  verbose: 1
  save_best_only: True
LROn:  
  monitor: "val_loss"
  factor: 0.1
  patience: 5
  min_lr: 0.000001
  verbose: 1
EarlyStopping:
  monitor: 'val_loss'
  patience: 20
  restore_best_weights: False
